idk

diff --git a/dotfiles/aliases b/dotfiles/aliases
--- a/dotfiles/aliases
+++ b/dotfiles/aliases
@@ -18,6 +18,11 @@ aa() {
   ar
 }
 
+role() {
+  account=$(jq -r 'keys[]' ~/.aws/accounts | fzf)
+  assume-role $account team-cloud $(botp)
+}
+
 sa() {
   script_name=$1
   script_path=$HOME/dotfiles/bin/$script_name
@@ -59,16 +64,13 @@ alias gfa="git fetch --all"
 alias glo="git log --oneline"
 alias gs="git status"
 alias gc="git commit"
-alias gz="gco master && git pull"
-alias gz!="git stash && gco master && git pull"
+alias gz="git stash && gco master && git pull"
 # TODO: move this to gitconfig
 alias noop="git checkout master && git pull && git checkout -b ml/noop && git commit --allow-empty -m \"noop\""
-
 
 pro() {
   hub pull-request --no-edit
 }
-
 
 prls() {
   hub pr list -h $(git branch-name)
@@ -142,8 +144,36 @@ mkscript() {
   chmod +x $script
 }
 
-function role() {
-  account=$(jq -r 'keys[]' ~/.aws/accounts | fzf)
-  assume-role $account team-cloud $(botp)
+function c() {
+  kill -9 $(jobs -p | cut -d " " -f 4)
+  clear
 }
 
+function hax() {
+  tmux new -A -s hax
+}
+
+function assume_role_from_sso() {
+  account_id=$1
+  role=$2
+
+  ROLE_SESSION_ARGS=(--role-arn arn:aws:iam::"${account_id}":role/"${role}")
+  ROLE_SESSION_ARGS+=(--external-id "${account_id}")
+  ROLE_SESSION_ARGS+=(--role-session-name "$INTERCOM_USER")
+  ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" || echo "fail")
+
+  if [ "$ROLE_SESSION" = "fail" ]; then
+    echo_out "Failed to export session envars."
+  else
+    AWS_ACCESS_KEY_ID=$(echo "$ROLE_SESSION" | jq -r .Credentials.AccessKeyId)
+    AWS_SECRET_ACCESS_KEY=$(echo "$ROLE_SESSION" | jq -r .Credentials.SecretAccessKey)
+    AWS_SESSION_TOKEN=$(echo "$ROLE_SESSION" | jq -r .Credentials.SessionToken)
+    export AWS_ACCESS_KEY_ID
+    export AWS_SECRET_ACCESS_KEY
+    export AWS_SESSION_TOKEN
+    export AWS_SECURITY_TOKEN=$AWS_SESSION_TOKEN
+    export AWS_ACCOUNT_ID="$account_id"
+    export AWS_ACCOUNT_ROLE="$role"
+    echo_out "Success! IAM session envars are exported."
+  fi
+}
